### ISSUE TITLE
[Merged on GitLab] Fix issue where a fixture status of None could not transition to Scheduled

### ISSUE THREAD

**Issue by sf-chris** [Sportsflare/bass-tube#138]
## Issue
We were unable to transition Fixture status where the existing `bass-tube` provider data had a status of `None`.

```
2022-04-21 00:45.49 [error    ] Failed to process task         error=ValueError('None is not a valid FixtureStatus') task_id=2493
Traceback (most recent call last):
  File "/bass-tube/bass_tube/reactor/__init__.py", line 61, in process_next_task
    result_status = await handle_fusion_task(conn, task)
  File "/bass-tube/bass_tube/reactor/handlers/fusion_task.py", line 75, in handle_fusion_task
    fused_data = fuse_fixture(strategy, provider_data_list)
  File "/bass-tube/bass_tube/fusion/__init__.py", line 74, in fuse_fixture
    fusion_result = field_fusion_strategy(provider_data_list)
  File "/bass-tube/bass_tube/fusion/strategies/fixture/__init__.py", line 92, in _f
    status = FixtureStatus(bass_tube.provider_data["status"])
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 663, in __new__
    raise ve_exc
ValueError: None is not a valid FixtureStatus
```

## Testing

'Fixed up' the problem fixture locally by triggering fusion
```
2022-04-21 02:34.14 [info     ] ☢ Reactor started ☢
2022-04-21 02:34.14 [info     ] Processing task                strategy_id=481 task_id=2497
2022-04-21 02:34.14 [info     ] Fusing data                    provider_data=[(4701, 'houston'), (4702, 'bass-tube'), (4707, 'hltv')] strategy_id=481 task_id=2497
2022-04-21 02:34.14 [info     ] Created new fused data row     data_row_id=4716 strategy_id=481 task_id=2497
2022-04-21 02:34.14 [info     ] Materialized fixture           fixture_id=472 strategy_id=481 task_id=2497
2022-04-21 02:34.14 [info     ] Task processed                 strategy_id=481 task_id=2497
```

Unit test replicates the issue that was happening in prod:
```
FAILED bass_tube/tests/fusion/strategies/fixture/test_fixture_strategies.py::test_transition_status_from_none_to_scheduled - ValueError: None is not a valid FixtureStatus
```

*Originally created on GitLab as an MR by steffansafey (https://gitlab.com/sportsflare/real-time/bass-tube/-/merge_requests/37) on 2022-04-21T02:39:06.680Z*

**Comment by sf-chris** [comment]
Sick bro LGTM

*Originally commented on GitLab by matt.cavill on 2022-04-21T03:21:10.773Z*
